global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'
  routes:
    - match:
        severity: critical
      receiver: 'telegram'
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'telegram'
      repeat_interval: 2h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: '${TELEGRAM_CHAT_ID}'
        parse_mode: 'HTML'
        disable_notifications: false
        message: |
          {{ if eq .CommonLabels.severity "critical" }}🔥 <b>CRITICAL ALERT: {{ .GroupLabels.alertname }}</b>{{ else if eq .CommonLabels.severity "warning" }}⚠️ <b>Warning: {{ .GroupLabels.alertname }}</b>{{ else }}🚨 <b>Alert: {{ .GroupLabels.alertname }}</b>{{ end }}
          
          <b>Status:</b> {{ .Status }}
          <b>Severity:</b> {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          <b>Summary:</b> {{ .Annotations.summary }}
          <b>Description:</b> {{ .Annotations.description }}
          <b>Instance:</b> {{ .Labels.instance }}
          <b>Job:</b> {{ .Labels.job }}
          <b>Time:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
